# -*- coding: utf-8 -*-
"""Dataset2hackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Q_AffPOGK37eLAW82gfoRd-uOZn1tsl
"""

#Link collab to drive
from google.colab import drive
drive.mount("/content/drive")

cd /content/drive/My\ Drive

import io
import pandas as pd

df=pd.read_csv("Ethnicitybygender.csv")
df #print data frame

"""Exploratory Data Analysis and Findings"""

df.info()
df.describe()



df_floats =df.iloc[0:22].drop(['Ethnic Group'], axis=1) #new dataframe created.head()
df_floats.columns

#Importing libraries for data visualization

import seaborn as sns
import matplotlib.pyplot as plt

df_floats.plot.barh(figsize=(28,10))
plt.rcParams["font.size"] =15

plt.title('COVID-19 Death Rate by Gender, age and Ethnicty by Population', fontdict={"fontname": "Arial", 'fontsize': 35})
plt.yticks(range(len(df)), df["Ethnic Group"])
plt.ylabel("Ethnic Group")
plt.xlabel("Proportion")

df_float.plot.line()

df_floats[['Males death rate ages:0-64',
       'Female Death rate 0-65', 'Males death rate ages:65+',
       'Females death rate ages:65+']].plot.barh(figsize=(25,10))
plt.rcParams["font.size"] = 20
plt.title('COVID-19 Death Rate by Gender, age and Ethnicty', fontdict={"fontname": "Arial", 'fontsize': 35})
plt.yticks(range(len(df)), df["Ethnic Group"])
plt.ylabel("Ethnic Group")
plt.xlabel("Proportion")