# -*- coding: utf-8 -*-
"""UK Data4Ethics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ugfZdXbeWdQbeMnS5icAqGrt_ndgKRs
"""

from google.colab import drive
drive.mount("/content/drive")

cd /content/drive/My\ Drive

import io
import pandas as pd

df = pd.read_csv("EthnictyDataset.csv")
df #mean display the whole graph

df =df.dropna(axis=0, how='all')
df

df.info()

df.columns

df.describe()

#Importing libraries for data visualization

dffloats = df.iloc[0:22].drop(['Ethnic Group'], axis=1) #new dataframe created
#dffloats['Ethnic Group'] = pd.CategoricalIndex(df['Ethnic Group']).codes

cols = dffloats.columns
dffloats[cols] = dffloats[cols].apply(pd.to_numeric, errors='coerce')

import seaborn as sns
import matplotlib.pyplot as plt

dffloats.info()

dffloats.head()

#Plotting a bunch of histograms
f, axes = plt.subplots(3, 4, figsize=(25, 10))#Setting a figure size
i = 0
j = 0
for column in dffloats.columns:
  if j <=3 :
    sns.distplot( dffloats[column], ax=axes[i, j], kde = False)
    j += 1
  else:
    i += 1
    j = 0
    sns.distplot( dffloats[column], ax=axes[i, j], kde = False) 
    j += 1
f.suptitle("X")
plt.show()

dframe=dffloats.drop(['COVID-19 deaths'], axis=1)
dframe.describe()

#fig = plt.figure(figsize=(45,20), facecolor=None )
dframe.plot.bar(figsize=(35,15))
plt.axhline(0, color='k');
plt.rcParams["font.size"] = 20

dframe[['Percentage of COVID-19 deaths']].plot.bar(figsize=(35,10))
plt.xticks(range(len(df)), df['Ethnic Group'], rotation=90)
plt.rcParams["font.size"] = 20
plt.title('Proportion of COVID-19 Deaths by ethnicity')

dffloats[['Main language is English/Welsh','Other main language: could speak English very well or well',
  'Other main language: could not speak English well',
  'Other main language: could not speak English']].plot.bar(figsize=(38,10))
plt.xticks(range(len(df)), df["Ethnic Group"])
plt.title('Level of English spoken by Ethnicity',fontdict={'fontsize': 35})
plt.xlabel('Ethnic group')

dffloats[['Percentage of COVID-19 deaths']].plot.line()

index = df['Ethnic Group']
dataplot = dframe.plot.barh()
#plot.tile('COVID-19 Death Rate features', fontdict=('fontname:' Tme))
#plt.xlabel(Ethnic Group)

dframe.plot.bar(x='Weighted Population in the UK', y='Percentage of COVID-19 deaths')

plt.style.available